---
efiBootLoader: "grub"
grubInstall: "/usr/sbin/grub-install"
grubMkconfig: "/usr/sbin/grub-mkconfig"
grubCfg: "/boot/grub/grub.cfg"
grubProbe: "/usr/sbin/grub-probe"
efiBootMgr: "/usr/sbin/efibootmgr"
kernelSearchPath:
  - "/usr/lib/modules"
  - "/boot"
kernelPattern: "^vmlinuz.*"
kernelParams: [ "quiet", "ro" ]
installEFIFallback: true
efiBootloaderId: "Calcium OS"
