---
overwrite: true
prefer_grub_d: false
keep_distributor: false
kernel_params: [ "quiet", "ro" ]
defaults:
  GRUB_TIMEOUT: 5
  GRUB_DEFAULT: "0"
  GRUB_GFXMODE: "auto"
  GRUB_GFXPAYLOAD_LINUX: "keep"
always_use_defaults: false
