---
defaultFileSystemType: "btrfs"
luksGeneration: "luks1"
userSwapChoices:
  - small
  - suspend
  - file
  - none
drawNestedPartitions: false
alwaysShowPartitionLabels: true
allowManualPartitioning: true
requiredPartitionTableType: "gpt"
efi:
  mountPoint: "/boot"
  partitionSize: 512M
  label: "CALCIUM_EFI"
partitionLayout:
  - name: "efi"
    type: "C12A7328-F81F-11D2-BA4B-00A0C93EC93B"
    filesystem: "fat32"
    mountPoint: "/boot"
    size: 512M
    minSize: 512M
  - name: "root"
    type: "0FC63DAF-8483-4772-8E79-3D69D8477DE4"
    filesystem: "btrfs"
    mountPoint: "/"
    size: 100%
    minSize: 10G
