---
services:
  - name: gdm
    runlevel: default
  - name: dbus
    runlevel: default
  - name: elogind
    runlevel: default
  - name: dhcpcd
    runlevel: default
  - name: cronie
    runlevel: default
  - name: netmount
    runlevel: default
  - name: ntpd
    runlevel: default
  - name: zram-init
    runlevel: boot
  - name: tailscale
    runlevel: default
