---
unpack:
  - source: "/"
    sourcefs: "file"
    destination: ""
    exclude:
      - "/proc/*"
      - "/sys/*"
      - "/dev/*"
      - "/run/*"
      - "/mnt/*"
      - "/tmp/*"
      - "/media/*"
      - "/lost+found"
      - "/swapfile"
      - "/home/livecd/.*"
      - "/home/livecd/.cache/*"
      - "/root/.cache/*"
      - "/var/cache/*"
      - "/var/tmp/*"
      - "/var/db/repos/*"
      - "/var/log/*"
      - "/boot/grub/*"
    weight: 100
