---
defaultGroups:
  - name: wheel
    must_exist: true
    system: true
  - name: audio
    must_exist: true
    system: true
  - name: video
    must_exist: true
    system: true
  - name: cdrom
    must_exist: true
    system: true
  - name: usb
    must_exist: true
    system: true
  - name: portage
    must_exist: false
    system: true
  - name: render
    must_exist: true
    system: true
sudoersGroup: "wheel"
autologinGroup: "autologin"
setRootPassword: true
doReusePassword: false
displayAutologin: true
doAutologin: true
passwordRequirements:
  minLength: 1
  maxLength: 0
allowWeakPasswords: true
user:
  shell: "/bin/zsh"
hostname:
  location: EtcFile
  writeHostsFile: true
