---
requirements:
  requiredStorage: 5.5
  requiredRam: 1.0
  internetCheckUrl: [ "http://google.com", "http://gentoo.org" ]
  check:
    - storage
    - ram
    - root
  required:
    - storage
    - ram
geoip:
  style: json
  url: "https://geoip.kde.org/v1/calamares"
