CHOST="x86_64-pc-linux-gnu"
CFLAGS="-march=x86-64 -O2 -pipe"
CXXFLAGS="${CFLAGS}"
MAKEOPTS="-j$(nproc)"
EMERGE_DEFAULT_OPTS="--jobs=$(nproc) --load-average=$(nproc) --quiet-build=n --with-bdeps=n --usepkg"

USE="udev openrc pam policykit -systemd -consolekit -X -gtk -gnome"

ACCEPT_LICENSE="*"
ACCEPT_KEYWORDS="amd64"

VIDEO_CARDS=""
INPUT_DEVICES="libinput keyboard mouse"
L10N="en en-US"

GENTOO_MIRRORS="https://distfiles.gentoo.org"
PORTAGE_BINHOST="https://distfiles.gentoo.org/releases/amd64/binpackages/23.0"
PORTAGE_TMPDIR="/var/tmp/portage"
DISTDIR="/var/cache/distfiles"
PKGDIR="/var/cache/binpkgs"

PORT_LOGDIR="/var/tmp/portage/log"
PORTAGE_ELOG_CLASSES="log warn error"
PORTAGE_ELOG_SYSTEM="echo"

FEATURES="buildpkg binpkg-multi-instance candy parallel-fetch parallel-install preserve-libs"
